name: Build, Lint, and Test

on:
  workflow_call:
    inputs:
      NPM_REGISTRY_NAME:
        type: string
        default: '@metamask'
      NPM_REGISTRY_URL:
        type: string
        required: false
        default: 'https://registry.npmjs.org'
      NPM_CLIENT:
        type: string
        default: 'yarn'

jobs:
  pipeline:
    name: Turbo Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          cache-node-modules: ${{ matrix.node-version == '22.x' }}
          submodules: 'recursive'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install npm dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run lint
        run: yarn lint
      
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi